"use client";
import { useCallback,useEffect,useState,useRef, type FormEvent } from "react";
import Link from "next/link";
import { AppShell } from "../AppShell";
import { LocationSafetyManager,useLocationSafety } from "../LocationSafetyManager";
import { RelocationPlanner } from "./RelocationPlanner";
import { HAZARDS,capacity,directions,risk,fresh,reservedStatuses,type Snapshot,type CaseRecord,type SiteInput,type Plan,type Role } from "@/shared/workflow/model";
const labels:Record<string,string>={flood:"Flood",landslide:"Landslide",coastalErosion:"Coastal erosion",cloudburst:"Cloudburst",land:"Land",water:"Water",sanitation:"Sanitation",shelter:"Shelter"};
const today=()=>new Date().toISOString().slice(0,10);
const empty:Snapshot={actor:null,localAvailable:false,cases:[],sites:[],plans:[],audit:[]};
function Field({name,label,value,type="number",max,min=0,step="1"}:{name:string;label:string;value?:string|number;type?:string;max?:number|string;min?:number;step?:string}){return <label className="wf-field">{label}<input name={name} type={type} defaultValue={value??""} required min={type==="number"?min:undefined} max={max} step={type==="number"?step:undefined} maxLength={type==="text"?200:undefined}/></label>;}
export function RelocationWorkspace(){
 const {location,selectLocation,data:live,loading:liveLoading}=useLocationSafety();
 const [data,setData]=useState<Snapshot>(empty),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[loaded,setLoaded]=useState(false),[tab,setTab]=useState("Assess"),[selected,setSelected]=useState(""),[editCase,setEditCase]=useState<CaseRecord|null>(null),[editSite,setEditSite]=useState<Partial<SiteInput>|null>(null),[note,setNote]=useState(""),[destination,setDestination]=useState(""),[offline,setOffline]=useState(false),[draft,setDraft]=useState<Record<string,unknown>|null>(null),[formKey,setFormKey]=useState(0);
 const pendingRequests=useRef(new Map<string,string>());
 // Map deep links select existing records; all recommendation and approval rules stay here.
 useEffect(()=>{const params=new URLSearchParams(window.location.search);const habitation=params.get("habitation"),site=params.get("site");if(habitation){setSelected(habitation);setTab("Recommend");}if(site){setDestination(site);if(!habitation)setTab("Sites");}},[]);
 const role=data.actor?.role;
 const refresh=useCallback(async()=>{try{const response=await fetch("/api/workflow",{cache:"no-store",signal:AbortSignal.timeout(15000)});const result=await response.json();if(!response.ok)throw new Error(result.error);setData(result);setLoaded(true);}catch(e){setMessage(e instanceof Error?e.message:"Cannot reach server");setLoaded(true);}},[]);
 useEffect(()=>{void refresh();const online=()=>{setOffline(!navigator.onLine);if(navigator.onLine)void refresh();};online();window.addEventListener("online",online);window.addEventListener("offline",online);const timer=setInterval(()=>{if(document.visibilityState==="visible")void refresh();},30000);return()=>{clearInterval(timer);window.removeEventListener("online",online);window.removeEventListener("offline",online);};},[refresh]);
 const mutate=async(body:Record<string,unknown>)=>{const fingerprint=JSON.stringify({body,role});const requestId=pendingRequests.current.get(fingerprint)??crypto.randomUUID();pendingRequests.current.set(fingerprint,requestId);setBusy(true);setMessage("");try{const r=await fetch("/api/workflow",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...body,requestId}),signal:AbortSignal.timeout(15000)});const result=await r.json();if(!r.ok){if(r.status<500)pendingRequests.current.delete(fingerprint);throw new Error(result.error);}pendingRequests.current.delete(fingerprint);if(body.action==="session"){setNote("");await refresh();}else setData(result);setMessage(body.action==="session"?"Prototype role session started.":"Saved. The audit trail has been updated.");return true;}catch(e){setMessage(e instanceof Error?e.message:"Connection failed. Nothing is confirmed until the server acknowledges it.");return false;}finally{setBusy(false);}};
 const readForm=(form:HTMLFormElement,kind:"case"|"site")=>{const f=new FormData(form);const number=(key:string)=>f.get(key)===""?null:Number(f.get(key));const common={name:f.get("name"),latitude:number("latitude"),longitude:number("longitude"),evidence:f.get("evidence"),assessedAt:f.get("assessedAt")};return kind==="case"?{...common,population:number("population"),vulnerable:number("vulnerable"),history:number("history"),hazards:Object.fromEntries(HAZARDS.map(h=>[h,number(h)])),...(editCase?{id:editCase.id,version:editCase.version}:{})}:{...common,...Object.fromEntries(["land","water","sanitation","shelter","occupied","hazard"].map(k=>[k,number(k)])),verified:f.get("verified")==="on",...(editSite?.id?{id:editSite.id,version:editSite.version}:{})};};
 const saveForm=async(e:FormEvent<HTMLFormElement>,kind:"case"|"site")=>{e.preventDefault();const input=readForm(e.currentTarget,kind);if(await mutate({action:kind==="case"?"saveCase":"saveSite",input})){setDraft(null);setEditCase(null);setEditSite(null);setFormKey(n=>n+1);}};
 const saveDraft=(form:HTMLFormElement|null,kind:string)=>{if(!form)return;try{localStorage.setItem("relocation-field-draft",JSON.stringify({schema:1,kind,values:Object.fromEntries(new FormData(form))}));setMessage("Draft saved on this device. It has not been submitted or approved.");}catch{setMessage("Device storage unavailable. Keep this page open or copy your inputs.");}};
 const restoreDraft=()=>{try{const saved=JSON.parse(localStorage.getItem("relocation-field-draft")||"null");if(saved?.schema!==1||!saved?.values||!["case","site"].includes(saved.kind))throw new Error();setEditCase(null);setEditSite(null);setDraft(saved.values);setTab(saved.kind==="case"?"Assess":"Sites");setFormKey(n=>n+1);setMessage("Draft restored as a new unsent assessment. Review before submitting.");}catch{setMessage("No valid local draft found.");}};
 const c=data.cases.find(c=>c.id===selected)??data.cases[0];
 const ranked=[...data.cases].sort((a,b)=>risk(b).score-risk(a).score||b.vulnerable-a.vulnerable);
 const plannedPeople=data.plans.filter(p=>reservedStatuses.includes(p.status)).reduce((n,p)=>n+p.population,0);
 const completed=data.plans.filter(p=>p.status==="Completed").reduce((n,p)=>n+p.population,0);
 const reviewed=data.plans.filter(p=>p.decisionSeconds!==undefined);
 const value=(key:string,fallback?:string|number)=>draft?.[key] as string|number|undefined??fallback;
 const openCase=(record:CaseRecord)=>{setEditCase(record);setDraft(null);setTab("Assess");setFormKey(n=>n+1);};
 const openSite=(record:Partial<SiteInput>)=>{setEditSite(record);setDraft(null);setTab("Sites");setFormKey(n=>n+1);};
 return <AppShell title="Proactive Relocation Workspace" description="Assess an at-risk habitation, verify destination capacity, obtain approval and track the move." actions={<button className="secondary-button" onClick={refresh} disabled={busy}>Refresh records</button>}>
 <div className="wf-workspace">
 <section className="content-card wf-intro"><div><span className="section-kicker">INPUT → PROCESSING → OUTPUT → FOLLOW-UP</span><h2>Move planning ahead of the disaster.</h2><p>Recurring floods, landslides, coastal erosion and cloudbursts threaten vulnerable communities. Connect field evidence, GIS screening, capacity checks and accountable relocation decisions in one workflow.</p></div><Link className="secondary-button" href="/resources">How this prototype works</Link></section>
 <section className="content-card wf-session"><div><strong>{data.actor?`${data.actor.local?"Local prototype · ":""}${role}`:"Choose a workflow session"}</strong><p>{data.actor?.local?"Supervised local role walkthrough. These are prototype records, not official evacuation orders. Role switching is disabled outside local development.":"Official workspaces require a signed-in account with a server-assigned workflow role."}</p></div>{data.localAvailable&&<label className="wf-field">Stakeholder role<select value={role??""} disabled={busy} onChange={e=>void mutate({action:"session",role:e.target.value})}><option value="" disabled>Select role</option><option value="officer">Field officer · assess and propose</option><option value="administrator">Administrator · review and approve</option><option value="coordinator">Coordinator · track the move</option></select></label>}{!data.actor&&!data.localAvailable&&loaded&&<Link href="/login" className="primary-button">Sign in</Link>}</section>
 {offline&&<p className="wf-warning" role="status">Offline. Save an input draft on this device; approvals require a server connection.</p>}{message&&<p className="wf-message" role="status">{message}</p>}
 {!loaded?<p>Loading saved workflow…</p>:data.actor&&<>
 <section className="wf-metrics"><article><span>Habitations assessed</span><strong>{data.cases.length}</strong></article><article><span>Red-zone review candidates</span><strong>{data.cases.filter(c=>risk(c).redZone).length}</strong></article><article><span>People with committed capacity</span><strong>{plannedPeople}</strong></article><article><span>People recorded relocated</span><strong>{completed}</strong></article></section>
 <nav className="segmented wf-tabs" aria-label="Relocation workflow">{["Assess","Sites","Recommend","Monitor"].map((name,i)=><button key={name} className={tab===name?"active":""} aria-pressed={tab===name} onClick={()=>{setTab(name);setDraft(null);}}>{i+1}. {name}</button>)}</nav>
 {(tab==="Assess"||tab==="Sites")&&<LocationSafetyManager/>}
 {tab==="Assess"&&<div className="wf-columns"><section className="content-card wf-card"><h2>{editCase?"Update habitation assessment":"1. Assess a habitation"}</h2><p>Use documented field evidence. Hazard intensity: 0 none, 1 low, 2 moderate, 3 substantial, 4 severe, 5 extreme. Missing values cannot be treated as zero.</p>{role!=="officer"?<p>Field officers submit and update assessments. Review the saved priority list alongside.</p>:<form key={`case-${formKey}`} onSubmit={e=>void saveForm(e,"case")}><div className="wf-form-grid"><Field name="name" label="Habitation name" type="text" value={value("name",editCase?.name)}/><Field name="population" label="People requiring relocation" min={1} max={1000000} value={value("population",editCase?.population)}/><Field name="latitude" label="Latitude" min={6} max={38} step="any" value={value("latitude",editCase?.latitude??location?.latitude)}/><Field name="longitude" label="Longitude" min={68} max={98} step="any" value={value("longitude",editCase?.longitude??location?.longitude)}/><Field name="vulnerable" label="Vulnerable people (unduplicated count)" max={1000000} value={value("vulnerable",editCase?.vulnerable)}/><Field name="history" label="Documented disasters in last 10 years" max={100} value={value("history",editCase?.history)}/>{HAZARDS.map(h=><Field key={h} name={h} label={`${labels[h]} intensity (0–5)`} max={5} value={value(h,editCase?.hazards[h])}/>)}<Field name="assessedAt" label="Assessment date" type="date" max={today()} value={value("assessedAt",editCase?.assessedAt??today())}/></div><label className="wf-field">Evidence reference and field observations<textarea name="evidence" required minLength={10} maxLength={1000} defaultValue={value("evidence",editCase?.evidence)} placeholder="Survey ID, authority report or source URL; date, assessor and relevant observations"/></label><div className="wf-actions"><button className="primary-button" disabled={busy||offline}>Save assessment</button><button type="button" className="secondary-button" onClick={e=>saveDraft(e.currentTarget.form,"case")}>Save device draft</button><button type="button" className="secondary-button" onClick={restoreDraft}>Restore draft</button><button type="button" className="secondary-button" onClick={()=>{setEditCase(null);setDraft(null);setFormKey(n=>n+1);}}>New assessment</button></div></form>}</section>
 <section className="content-card wf-card"><h2>Habitation priority list</h2><p>Highest screening score first, then vulnerable population. Red-zone candidates require authority review.</p>{!ranked.length&&<p>No assessments yet. Begin with a field record; no example populations are preloaded.</p>}{ranked.map(h=><article className="wf-record" key={h.id}><strong>{h.name} <span className={risk(h).redZone?"wf-critical":""}>{risk(h).score}/100 · {risk(h).category}</span></strong><p>{h.population} people · {h.vulnerable} vulnerable · {risk(h).confidence}</p><div className="wf-actions"><button className="secondary-button" onClick={()=>{setSelected(h.id);setTab("Recommend");}}>Review options</button>{role==="officer"&&<button className="secondary-button" onClick={()=>openCase(h)}>Edit</button>}<button className="secondary-button" onClick={()=>selectLocation({latitude:h.latitude,longitude:h.longitude,name:h.name})}>Load live context</button></div></article>)}
 {location&&<p className="source-note">Selected location: {location.name??`${location.latitude.toFixed(3)}, ${location.longitude.toFixed(3)}`} · Weather {live?.weather.status??"not loaded"} · NDMA {live?.alerts.status??"not loaded"}. Live context does not silently overwrite field assessments.</p>}</section></div>}
 {tab==="Sites"&&<div className="wf-columns"><section className="content-card wf-card"><h2>2. Verify an alternative site</h2><p>Each capacity is a field-supported maximum number of people. The lowest limit controls carrying capacity. Baseline occupancy excludes reservations recorded in this workspace.</p>{role!=="officer"?<p>Only a field officer can register or revise site evidence.</p>:<form key={`site-${formKey}`} onSubmit={e=>void saveForm(e,"site")}><div className="wf-form-grid"><Field name="name" label="Site name" type="text" value={value("name",editSite?.name)}/><Field name="latitude" label="Latitude" min={6} max={38} step="any" value={value("latitude",editSite?.latitude??location?.latitude)}/><Field name="longitude" label="Longitude" min={68} max={98} step="any" value={value("longitude",editSite?.longitude??location?.longitude)}/>{(["land","water","sanitation","shelter"] as const).map(k=><Field key={k} name={k} label={`${labels[k]} capacity (people)`} max={1000000} value={value(k,editSite?.[k])}/>)}<Field name="occupied" label="Baseline occupants (people)" max={1000000} value={value("occupied",editSite?.occupied)}/><Field name="hazard" label="Maximum assessed site hazard (0–5)" max={5} value={value("hazard",editSite?.hazard)}/><Field name="assessedAt" label="Field verification date" type="date" max={today()} value={value("assessedAt",editSite?.assessedAt??today())}/></div><label className="wf-field">Evidence for safety, access and capacity<textarea name="evidence" required minLength={10} maxLength={1000} defaultValue={value("evidence",editSite?.evidence)} placeholder="Inspection reference, capacity calculations and access checks"/></label><label className="wf-check"><input type="checkbox" name="verified" defaultChecked={draft?draft.verified==="on":editSite?.verified??false}/>Field inspection supports site safety and access at this date</label><div className="wf-actions"><button className="primary-button" disabled={busy||offline}>Save site evidence</button><button type="button" className="secondary-button" onClick={e=>saveDraft(e.currentTarget.form,"site")}>Save device draft</button><button type="button" className="secondary-button" onClick={restoreDraft}>Restore draft</button><button type="button" className="secondary-button" onClick={()=>{setEditSite(null);setDraft(null);setFormKey(n=>n+1);}}>New site</button></div></form>}</section>
 <section className="content-card wf-card"><h2>Saved site capacity</h2>{data.sites.map(s=>{const reserved=data.plans.filter(p=>p.siteId===s.id&&reservedStatuses.includes(p.status)).reduce((n,p)=>n+p.population,0);return <article className="wf-record" key={s.id}><strong>{s.name}</strong><p>{capacity(s)} total − {s.occupied} baseline − {reserved} committed = <b>{Math.max(0,capacity(s)-s.occupied-reserved)} available</b></p><p>{s.verified?"Officer verified":"Verification pending"} · {fresh(s.assessedAt)?"Current evidence":"Reassessment required"}</p>{role==="officer"&&<button className="secondary-button" onClick={()=>openSite(s)}>Edit evidence</button>}</article>;})}
 <h3>Discover mapped facilities</h3><p>Use an OpenStreetMap location as a starting point. Capacity and safety must be verified before it can qualify.</p>{liveLoading?<p>Loading nearby records…</p>:!location?<p>Select a location above.</p>:live?.facilities.status==="unavailable"?<p>Facility provider unavailable. You can enter a surveyed site manually.</p>:live?.facilities.data.slice(0,8).map(s=><article className="wf-record" key={s.id}><strong>{s.name}</strong><p>{s.type} · {s.distanceKm.toFixed(1)} km straight-line · capacity unknown</p>{role==="officer"&&<button className="secondary-button" onClick={()=>openSite({name:s.name,latitude:s.latitude,longitude:s.longitude,evidence:`Map reference: ${s.sourceUrl}. Add field verification and capacity evidence.`,verified:false})}>Assess this site</button>}</article>)}</section></div>}
 {tab==="Recommend"&&c&&<RelocationPlanner caseRecord={c} role={role} busy={busy} offline={offline} onPropose={async siteId=>{if(await mutate({action:"propose",caseId:c.id,siteId,note:"Submitted for administrator review"}))setTab("Monitor");}}/>}
 {tab==="Monitor"&&<><section className="content-card wf-card"><h2>4. Review, confirm and track</h2><p>Administrator: review and approve. Coordinator: record departure and completion. Approval atomically reserves capacity; completed moves continue to consume site capacity.</p><label className="wf-field">Decision / progress note<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={1000} placeholder="Record verification, decision or arrival confirmation (10+ characters)"/></label><p>Average submission-to-approval time: {reviewed.length?`${Math.round(reviewed.reduce((n,p)=>n+(p.decisionSeconds??0),0)/reviewed.length)} seconds`:"No approvals yet"} · Pending reviews: {data.plans.filter(p=>p.status==="Pending").length} · Completion: {plannedPeople?Math.round(completed/plannedPeople*100):0}% of committed people.</p></section>
 {!data.plans.length&&<p>No plans yet. A field officer submits an eligible recommendation in step 3.</p>}{[...data.plans].reverse().map(p=>{const origin=data.cases.find(c=>c.id===p.caseId),site=data.sites.find(s=>s.id===p.siteId);const actions:Plan["status"][]=role==="administrator"?(p.status==="Pending"?["Approved","Rejected","Cancelled"]:p.status==="Approved"?["Cancelled"]:[]):role==="coordinator"?(p.status==="Approved"?["Moving"]:p.status==="Moving"?["Completed"]:[]):[];return <section className="content-card wf-card" key={p.id}><span className="section-kicker">{p.status} · {p.id.slice(0,8)}</span><h3>{origin?.name} → {site?.name}</h3><p>{p.population} people · submitted {new Date(p.createdAt).toLocaleString()} · {p.note}</p>{origin&&site&&<details><summary>Review assessment and destination evidence</summary><p>Submitted habitation evidence: {p.caseSnapshot?.evidence??origin.evidence}</p><p>Submitted destination evidence: {p.siteSnapshot?.evidence??site.evidence}</p><p>Current field dates: {origin.assessedAt} / {site.assessedAt}. Versions submitted: {p.caseVersion} / {p.siteVersion}; current: {origin.version} / {site.version}. Changed evidence blocks approval or departure.</p><p>Risk {risk(origin).score}/100. Carrying capacity {capacity(site)} people; baseline occupancy {site.occupied}. Latest available capacity is checked again at approval.</p></details>}{origin&&site&&!["Cancelled","Rejected","Completed"].includes(p.status)&&(!fresh(origin.assessedAt)||!fresh(site.assessedAt)||origin.version!==p.caseVersion||site.version!==p.siteVersion||!site.verified||site.hazard>1)&&<p className="wf-warning">Evidence changed or expired. Administrator reassessment required.</p>}<div className="wf-actions">{actions.map(status=><button key={status} className="primary-button" disabled={busy||offline||note.trim().length<10} onClick={()=>void mutate({action:"transition",id:p.id,status,note})}>{status==="Approved"?"Approve & reserve capacity":status==="Moving"?"Confirm departure":status==="Completed"?"Confirm arrival":status=== "Rejected"?"Reject":"Cancel & release"}</button>)}{origin&&site&&["Approved","Moving","Completed"].includes(p.status)&&<a href={directions(origin,site)} target="_blank" rel="noopener noreferrer" className="secondary-button">Open Google Maps directions ↗</a>}<button className="secondary-button" onClick={()=>{const text=JSON.stringify({prototype:data.actor?.local,plan:p,habitation:origin,site,audit:data.audit.filter(a=>a.target===p.id)},null,2);const url=URL.createObjectURL(new Blob([text],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=`relocation-${p.id.slice(0,8)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Export decision record</button></div></section>;})}
 <section className="content-card wf-card"><h2>Audit trail</h2><p>Server-recorded actor, role, action and time. Latest 200 events.</p><div className="wf-audit">{data.audit.map(a=><p key={a.id}><time>{new Date(a.at).toLocaleString()}</time> · <b>{a.role}</b> · {a.action} · {a.target.slice(0,8)}<br/>{a.note}</p>)}</div></section></>}
 </>}
 </div></AppShell>;
}
