"use client";
import { usePreferences } from "./AppPreferences";

import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { RISK_STYLES } from "@/config/risk";
import type { DashboardSummary, Habitation } from "@/types/disaster";

export function DashboardCharts({ habitations, summary }: { habitations: Habitation[]; summary: DashboardSummary }) {
  const { tr } = usePreferences();
  const riskData = (["SAFE", "MODERATE", "HIGH", "RED"] as const).map((category) => ({ name: tr(RISK_STYLES[category].label), value: habitations.filter((item) => item.risk_category === category).length, color: RISK_STYLES[category].color }));
  const populationData = (["SAFE", "MODERATE", "HIGH", "RED"] as const).map((category) => ({ name: tr(RISK_STYLES[category].label), population: habitations.filter((item) => item.risk_category === category).reduce((sum, item) => sum + item.population, 0), fill: RISK_STYLES[category].color }));
  const capacityData = [{ name: tr("Immediate need"), value: summary.immediate_relocation_population, fill: "#c83f49" }, { name: tr("Safe capacity"), value: summary.total_available_capacity, fill: "#23845e" }];
  return <div className="chart-grid"><section className="content-card chart-card"><div className="card-heading"><div><span className="section-kicker">{tr("RISK DISTRIBUTION")}</span><h2>{tr("Habitation classification")}</h2></div></div><div className="chart-with-legend"><div className="pie-chart"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={riskData} dataKey="value" nameKey="name" innerRadius={48} outerRadius={72} paddingAngle={3}>{riskData.map((item) => <Cell key={item.name} fill={item.color} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div><div className="chart-side-legend">{riskData.map((item) => <div key={item.name}><i style={{ background: item.color }} /><span>{item.name}</span><strong>{item.value}</strong></div>)}</div></div></section><section className="content-card chart-card"><div className="card-heading"><div><span className="section-kicker">{tr("POPULATION BY RISK")}</span><h2>{tr("Exposure profile")}</h2></div></div><div className="bar-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={populationData} margin={{ left: -10, right: 8, top: 8 }}><CartesianGrid vertical={false} stroke="#e7edef" /><XAxis dataKey="name" tick={{ fontSize: 10 }} axisLine={false} tickLine={false} /><YAxis tick={{ fontSize: 10 }} axisLine={false} tickLine={false} /><Tooltip formatter={(value) => Number(value).toLocaleString("en-IN")} /><Bar dataKey="population" radius={[5, 5, 0, 0]}>{populationData.map((item) => <Cell key={item.name} fill={item.fill} />)}</Bar></BarChart></ResponsiveContainer></div></section><section className="content-card chart-card capacity-chart"><div className="card-heading"><div><span className="section-kicker">{tr("RELOCATION CAPACITY")}</span><h2>{tr("Immediate need vs assessed capacity")}</h2></div></div><div className="bar-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={capacityData} layout="vertical" margin={{ left: 10, right: 20 }}><CartesianGrid horizontal={false} stroke="#e7edef" /><XAxis type="number" tick={{ fontSize: 10 }} axisLine={false} tickLine={false} /><YAxis type="category" dataKey="name" width={90} tick={{ fontSize: 10 }} axisLine={false} tickLine={false} /><Tooltip formatter={(value) => Number(value).toLocaleString("en-IN")} /><Bar dataKey="value" radius={[0, 5, 5, 0]}>{capacityData.map((item) => <Cell key={item.name} fill={item.fill} />)}</Bar></BarChart></ResponsiveContainer></div></section></div>;
}
