"use client";
import { useEffect, useState } from "react";
import { X, ArrowRight, Bot } from "lucide-react";
import type { Habitation, RelocationRecommendation } from "@/types/disaster";
import { RiskBadge } from "./RiskBadge";
import { RiskExplanation } from "./RiskExplanation";
import { CurrentConditions } from "./CurrentConditions";
export function HabitationDetailPanel({habitation:h,recommendation:r,onClose,onFindRelocation,inline=false}:{habitation:Habitation;recommendation:RelocationRecommendation|null;onClose:()=>void;onFindRelocation:()=>void;inline?:boolean}){
 const [tab,setTab]=useState("Overview");
 useEffect(()=>setTab("Overview"),[h.id]);
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose();};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close);},[onClose]);
 return <>{!inline&&<button className="drawer-scrim" aria-label="Close habitation details" onClick={onClose}/>}<aside className={inline?"detail-drawer inline-detail":"detail-drawer"} aria-label={h.name+" risk analysis"}><div className="panel-title"><div><h2>{h.name}</h2><p>{h.district}, {h.state}</p></div><button className="icon-button" aria-label="Close" onClick={onClose}><X size={16}/></button></div><div className="segmented" role="tablist" aria-label="Habitation details">{["Overview","Risk","History","Relocation"].map(t=><button key={t} role="tab" aria-selected={tab===t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{t}</button>)}</div><div role="tabpanel">
 {tab==="Overview"&&<><dl className="plan-facts"><div><dt>Population</dt><dd>{h.population.toLocaleString("en-IN")}</dd></div><div><dt>Households</dt><dd>Not available</dd></div><div><dt>Elevation</dt><dd>Not available</dd></div><div><dt>Primary Livelihood</dt><dd>Not available</dd></div></dl><h3>Hazards Affecting</h3><ul className="hazard-list">{[["Landslide",h.landslide_risk],["Flood",h.flood_risk],["Cloudburst",h.cloudburst_risk]].map(([label,score])=><li key={label}><i className={Number(score)>70?"red":Number(score)>40?"amber":"green"}/>{label} exposure · {Number(score)>70?"High":Number(score)>40?"Moderate":"Low"}</li>)}</ul><div className="risk-total"><span>Risk Score<strong>{h.risk_score} / 100</strong></span><RiskBadge value={h.risk_category}/></div><button className="primary-button full" onClick={()=>setTab("Risk")}>View Explainable Risk <ArrowRight size={15}/></button></>}
 {tab==="Risk"&&<><RiskExplanation habitation={h}/><button className="primary-button full" onClick={()=>setTab("Relocation")}>Assess relocation options <ArrowRight size={15}/></button></>}
 {tab==="History"&&<><h3>Disaster history</h3><div className="risk-total"><span>Recorded demo events<strong>{h.past_disasters}</strong></span></div><p className="source-note">Event dates and individual incident records are not available. Dataset release: {h.last_updated.slice(0,10)}.</p><CurrentConditions key={h.id} habitation={h}/></>}
 {tab==="Relocation"&&<><h3>Recommended Safe Site</h3>{r?<><div className="destination-card"><span>CAPACITY-CHECKED CANDIDATE</span><h2>{r.site_name}</h2><p>{r.suitability_score}/100 suitability</p></div><dl className="plan-facts"><div><dt>Distance · straight line</dt><dd>{r.distance_km} km</dd></div><div><dt>Available capacity</dt><dd>{(r.remaining_capacity_after+h.population).toLocaleString("en-IN")}</dd></div><div><dt>After proposed move</dt><dd>{r.remaining_capacity_after.toLocaleString("en-IN")}</dd></div></dl></>:<p>No capacity-checked recommendation available.</p>}<button className="primary-button full" onClick={onFindRelocation}>Find Best Sites <ArrowRight size={15}/></button><p className="source-note">Estimated demo capacity. Shelter readiness and route safety require verification.</p></>}
 </div><button className="panel-ai" onClick={()=>window.dispatchEvent(new CustomEvent("suraksha-ai-habitation",{detail:{id:h.id,name:h.name}}))}><Bot size={14}/>Ask AI about {h.name}</button></aside></>;
}

