import Image from "next/image";
import Link from "next/link";
import { ArrowRight, MapPinned, Layers3, ShieldCheck, MoveUpRight } from "lucide-react";
import { Header } from "./Header";
import { LocalSafetyPanel } from "./LocalSafetyPanel";

export function LandingPage() {
  return <div className="landing"><Header /><LocalSafetyPanel /><main className="terrain-hero"><Image src="/terrain-hero.png" alt="Illustrative Himalayan mountain landscape" fill priority sizes="100vw" className="hero-image" /><div className="hero-shade" /><div className="hero-content"><span className="hero-eyebrow"><i />MULTI-HAZARD INTELLIGENCE · INDIA</span><h1><span>Safer Communities.</span><br />A More Resilient<br className="mobile-break" /> Tomorrow.</h1><p>Identify vulnerable habitations, assess safer destinations and coordinate accountable relocation — before the next disaster.</p><div className="hero-actions"><Link href="/relocation" className="primary-button">Plan Relocation <ArrowRight size={17} /></Link><Link href="/map" className="secondary-button">View Live Map <MoveUpRight size={16} /></Link></div><div className="hero-pillars"><span><Layers3 size={16} />Multi-Hazard Intelligence</span><span><MapPinned size={16} />GIS Decision Support</span><span><ShieldCheck size={16} />Verified Capacity</span></div></div><div className="hero-bottom"><span>PEOPLE × PLACES × PLANS</span><span>COMMUNITY RESILIENCE · SIH26191</span><span>DATA × SCIENCE × POLICY × IMPACT</span></div></main><section className="prototype-story"><span className="section-kicker">PROACTIVE RELOCATION · CONNECTED DECISIONS</span><h2>From vulnerable habitation to a reviewed relocation plan.</h2><p>Floods, landslides, coastal erosion and cloudbursts repeatedly threaten communities. GeoKavach brings field evidence, capacity checks and administrative approval into one GIS-enabled workflow, so planning can begin before tragedy strikes.</p><div className="wf-site-grid"><article><h3>01 · Assess the need</h3><p>A field officer records the affected population, hazard intensity, vulnerability and disaster history with dated evidence.</p></article><article><h3>02 · Screen alternatives</h3><p>Explainable rules prioritize habitations and exclude destinations without current verification or enough carrying capacity.</p></article><article><h3>03 · Review and approve</h3><p>An administrator reviews the evidence, confirms the destination and reserves capacity with an auditable decision.</p></article><article><h3>04 · Coordinate and monitor</h3><p>Open directions, record departure and arrival, and measure people relocated and time to approval.</p></article></div><div className="hero-actions"><Link href="/relocation" className="primary-button">Start assessment →</Link><Link href="/resources" className="secondary-button">Methodology & prototype limits</Link></div></section></div>;
}
