import test from "node:test";
import assert from "node:assert/strict";
import {WorkflowStore} from "../src/backend/workflow/store";
import {parseCase,parseSite} from "../src/backend/workflow/validation";
import {risk,candidates,capacity,type Actor} from "../src/shared/workflow/model";
const officer:Actor={id:"test-officer",role:"officer",workspace:"test",local:false};
const admin:Actor={...officer,id:"test-admin",role:"administrator"};
const coordinator:Actor={...officer,id:"test-coordinator",role:"coordinator"};
const date=new Date().toISOString().slice(0,10);
const habitation={name:"Test habitation",latitude:30.1,longitude:79.1,population:100,vulnerable:50,history:4,hazards:{flood:5,landslide:4,coastalErosion:0,cloudburst:2},evidence:"TEST ONLY: documented assessment",assessedAt:date};
const site={name:"Test destination",latitude:30.15,longitude:79.15,land:180,water:150,sanitation:160,shelter:170,occupied:0,hazard:1,verified:true,evidence:"TEST ONLY: site assessment",assessedAt:date};
function setup(){const store=new WorkflowStore(":memory:");store.mutate(officer,{action:"saveCase",input:habitation});store.mutate(officer,{action:"saveSite",input:site});return store;}
test("relocation: invalid and missing evidence never become zero-valued assessments",()=>{assert.throws(()=>parseCase({...habitation,population:0}));assert.throws(()=>parseCase({...habitation,vulnerable:101}));assert.throws(()=>parseCase({...habitation,hazards:{}}));assert.throws(()=>parseSite({...site,evidence:""}));assert.throws(()=>parseSite({...site,occupied:151}));assert.equal(capacity(site),150);assert.equal(risk(habitation).score,82);});
test("relocation: stale, unverified, exposed and undersized destinations are excluded",()=>{const store=setup();try{const {cases,sites}=store.snapshot(officer);for(const change of [{verified:false},{hazard:2},{water:50},{assessedAt:"2000-01-01"}])assert.equal(candidates(cases[0],[{...sites[0],...change}],[])[0].eligible,false);assert.equal(candidates({...cases[0],assessedAt:"2000-01-01"},sites,[])[0].eligible,false);}finally{store.close();}});
test("relocation: end-to-end roles, approval, committed capacity and audit",()=>{const store=setup();try{const {cases,sites}=store.snapshot(officer);assert.throws(()=>store.mutate(admin,{action:"saveCase",input:habitation}),/Only the officer/);store.mutate(officer,{action:"propose",caseId:cases[0].id,siteId:sites[0].id});const p=store.snapshot(officer).plans[0];assert.throws(()=>store.mutate(officer,{action:"transition",id:p.id,status:"Approved",note:"Review confirmed"}),/administrator/);store.mutate(admin,{action:"transition",id:p.id,status:"Approved",note:"Evidence reviewed and accepted"});assert.equal(candidates(cases[0],sites,store.snapshot(officer).plans)[0].available,50);store.mutate(coordinator,{action:"transition",id:p.id,status:"Moving",note:"Departure confirmed by coordinator"});assert.throws(()=>store.mutate(admin,{action:"transition",id:p.id,status:"Cancelled",note:"Cannot silently free moving people"}),/already moving/);store.mutate(coordinator,{action:"transition",id:p.id,status:"Completed",note:"Arrival confirmed with headcount"});assert.equal(store.snapshot(officer).plans[0].status,"Completed");assert.equal(store.snapshot(officer).audit.length,6);assert.throws(()=>store.mutate(coordinator,{action:"transition",id:p.id,status:"Completed",note:"Repeated request"}),/Invalid/);assert.equal(store.snapshot({...officer,workspace:"other"}).cases.length,0);}finally{store.close();}});
test("relocation: pending proposals cannot double-book on approval",()=>{const store=setup();try{store.mutate(officer,{action:"saveCase",input:{...habitation,name:"Second test habitation"}});const {cases,sites}=store.snapshot(officer);for(const c of cases)store.mutate(officer,{action:"propose",caseId:c.id,siteId:sites[0].id});const [a,b]=store.snapshot(officer).plans;store.mutate(admin,{action:"transition",id:a.id,status:"Approved",note:"First allocation reviewed"});assert.throws(()=>store.mutate(admin,{action:"transition",id:b.id,status:"Approved",note:"Second allocation reviewed"}),/Insufficient/);assert.equal(store.snapshot(officer).plans.find(p=>p.id===b.id)?.status,"Pending");}finally{store.close();}});
test("relocation: changed evidence blocks pending approval, version conflicts preserve records",()=>{const store=setup();try{const {cases,sites}=store.snapshot(officer);store.mutate(officer,{action:"propose",caseId:cases[0].id,siteId:sites[0].id});const p=store.snapshot(officer).plans[0];store.mutate(officer,{action:"saveSite",input:{...sites[0],evidence:"Updated TEST evidence reference"}});assert.throws(()=>store.mutate(admin,{action:"transition",id:p.id,status:"Approved",note:"Review changed assessment"}),/Assessment changed/);assert.throws(()=>store.mutate(officer,{action:"saveSite",input:sites[0]}),/record changed/);assert.equal(store.snapshot(officer).sites[0].version,2);}finally{store.close();}});
test("relocation: retry keys prevent duplicate records and reject mismatched retries",()=>{const store=new WorkflowStore(":memory:");try{const request={action:"saveCase",input:habitation,requestId:"test-idempotency-key"};store.mutate(officer,request);store.mutate(officer,request);assert.equal(store.snapshot(officer).cases.length,1);assert.equal(store.snapshot(officer).audit.length,1);assert.throws(()=>store.mutate(officer,{...request,input:{...habitation,name:"Changed request"}}),/reused/);}finally{store.close();}});
test("relocation: proposed evidence is immutable and committed capacity cannot be reduced",()=>{const store=setup();try{const {cases,sites}=store.snapshot(officer);store.mutate(officer,{action:"propose",caseId:cases[0].id,siteId:sites[0].id});const p=store.snapshot(officer).plans[0];assert.equal(p.caseSnapshot?.evidence,habitation.evidence);store.mutate(admin,{action:"transition",id:p.id,status:"Approved",note:"Test evidence reviewed"});assert.throws(()=>store.mutate(officer,{action:"saveSite",input:{...sites[0],water:50}}),/committed/);store.mutate(officer,{action:"saveSite",input:{...sites[0],evidence:"Updated field reference in test"}});assert.equal(store.snapshot(officer).plans[0].siteSnapshot?.evidence,site.evidence);}finally{store.close();}});
